apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: dblp-neo4j
  name: dblp-neo4j
  namespace: adv-da-ba23-chb
spec:
  ports:
    - name: "7474"
      port: 7474
      targetPort: 7474
    - name: "7687"
      port: 7687
      targetPort: 7687
  selector:
    io.kompose.service: dblp-neo4j
status:
  loadBalancer: {}
