apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: dblp-neo4j
  name: dblp-neo4j
  namespace: adv-da-ba23-chb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dblp-neo4j
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: dblp-neo4j
    spec:
      containers:
        - env:
            - name: NEO4J_AUTH
              value: neo4j/neo4j_password
            - name: NEO4J_server_config_strict__validation_enabled
              value: "false"
          image: neo4j:latest
          name: dblp-neo4j
          ports:
            - containerPort: 7474
            - containerPort: 7687
          resources:
            limits:
              memory: 2Gi
      restartPolicy: Always
status: {}
